{
    "infos": [
        {
            "key": "ERROR_CONNECT",
            "value": "Failed to connect to the server."
        },
        {
            "key": "MAINTENANCE",
            "value": "Conducting maintenance. <br>Check the Notices page for details."
        },
        {
            "key": "ACCOUNT_BAN",
            "value": "Account suspended."
        },
        {
            "key": "VERSION_UPDATE",
            "value": "Please update to the newest version."
        },
        {
            "key": "DLC_UPDATE",
            "value": "DLC updates are available."
        },
        {
            "key": "SESSION_ERROR",
            "value": "Invalid session."
        },
        {
            "key": "INVALID_DEVICE",
            "value": "No game account detected. <br>Account will be reset."
        },
        {
            "key": "NOTICE",
            "value": "This function is temporarily disabled. <br>Check the Notices page for details."
        },
        {
            "key": "TITLE_NOTICE",
            "value": "Notices"
        },
        {
            "key": "OVER_DAY",
            "value": "A new day has begun."
        },
        {
            "key": "TITLE_OVER_DAY",
            "value": "Date Change"
        },
        {
            "key": "CONNECT_DEVICE_DOES_NOT_EXIST",
            "value": "No game account detected."
        },
        {
            "key": "HAS_ADD_DEVICE_CONNECT_NOT_FOUND",
            "value": "No data link information found."
        },
        {
            "key": "HAS_IDPW_USER_NOT_FOUND",
            "value": "No data link user found."
        },
        {
            "key": "HAS_IDPW_INVALID_SCHEMA",
            "value": "Data link password type is unauthorized."
        },
        {
            "key": "HAS_IDPW_VERIFY_FAILES",
            "value": "Data link confirmation error."
        },
        {
            "key": "HAS_BRIDGE_USER_NOT_FOUND",
            "value": "Not registered to SQUARE ENIX BRIDGE."
        },
        {
            "key": "HAS_BRIDGE_FAILES_TITLE",
            "value": "Process Terminated"
        },
        {
            "key": "HAS_BRIDGE_FAILES",
            "value": "The process was terminated before it could be completed. <br>If this was not intentional, it was likely caused by an error. <br>Please inquire with Support via the Title screen for further details or clarification."
        },
        {
            "key": "APP_ERROR_UNKNOWN",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_10",
            "value": "An error has occurred with your purchase.<br>It may take some time before your purchase appears in the game.<br><br>Please restart the game and/or your device<br>and check again."
        },
        {
            "key": "APP_ERROR_501",
            "value": "Insufficient coins/medals."
        },
        {
            "key": "APP_ERROR_502",
            "value": "Insufficient items."
        },
        {
            "key": "APP_ERROR_503",
            "value": "You cannot carry any more gil."
        },
        {
            "key": "APP_ERROR_505",
            "value": "Unknown reward."
        },
        {
            "key": "APP_ERROR_506",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_507",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_508",
            "value": "Insufficient gil."
        },
        {
            "key": "APP_ERROR_511",
            "value": "Data Error: Issue(s) detected in clear data."
        },
        {
            "key": "APP_ERROR_1000",
            "value": "Account does not exist."
        },
        {
            "key": "APP_ERROR_1001",
            "value": "You cannot receive any more NRG."
        },
        {
            "key": "APP_ERROR_1002",
            "value": "NRG restoration limit exceeded. (Visiore)"
        },
        {
            "key": "APP_ERROR_1003",
            "value": "NRG restoration limit exceeded. (Items)"
        },
        {
            "key": "APP_ERROR_1004",
            "value": "Arena Orb restoration limit exceeded. (Visiore)"
        },
        {
            "key": "APP_ERROR_1005",
            "value": "Arena Orb restoration limit exceeded. (Items)"
        },
        {
            "key": "APP_ERROR_1006",
            "value": "There is a 10 day cooldown period after changing your Player Name before you are able to change it again.<br><br>However, players of Royal Rank 2 or higher are exempt from this period."
        },
        {
            "key": "APP_ERROR_1007",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_1008",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_1009",
            "value": "Name not found."
        },
        {
            "key": "APP_ERROR_1010",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_1100",
            "value": "Unknown unit."
        },
        {
            "key": "APP_ERROR_1101",
            "value": "Unknown Job."
        },
        {
            "key": "APP_ERROR_1102",
            "value": "Unknown ability."
        },
        {
            "key": "APP_ERROR_1103",
            "value": "Unit's level is insufficient."
        },
        {
            "key": "APP_ERROR_1104",
            "value": "Unit's JP is insufficient."
        },
        {
            "key": "APP_ERROR_1105",
            "value": "Unit's Job level is insufficient."
        },
        {
            "key": "APP_ERROR_1106",
            "value": "Unit's proficiency level is insufficient."
        },
        {
            "key": "APP_ERROR_1107",
            "value": "Selected unit cannot be trained."
        },
        {
            "key": "APP_ERROR_1108",
            "value": "Job cannot be set."
        },
        {
            "key": "APP_ERROR_1109",
            "value": "Unit is fully awakened."
        },
        {
            "key": "APP_ERROR_1110",
            "value": "Unit's Limit Break maxed out."
        },
        {
            "key": "APP_ERROR_1111",
            "value": "Unit's Job level maxed out."
        },
        {
            "key": "APP_ERROR_1112",
            "value": "Unit's awakening is not sufficient enough for Limit Break."
        },
        {
            "key": "APP_ERROR_1113",
            "value": "Ability's level maxed out."
        },
        {
            "key": "APP_ERROR_1114",
            "value": "Selected ability cannot be set as a Support Ability."
        },
        {
            "key": "APP_ERROR_1115",
            "value": "Selected ability cannot be set as a Reaction Ability."
        },
        {
            "key": "APP_ERROR_1116",
            "value": "Selected ability cannot be set."
        },
        {
            "key": "APP_ERROR_1117",
            "value": "Selected ability is equipped to another slot."
        },
        {
            "key": "APP_ERROR_1118",
            "value": "Selected Ability Board is already unlocked."
        },
        {
            "key": "APP_ERROR_1119",
            "value": "Selected unit does not possess a Master Ability."
        },
        {
            "key": "APP_ERROR_1120",
            "value": "Selected unit does not possess a Limit Burst."
        },
        {
            "key": "APP_ERROR_1121",
            "value": "Unit's Limit Burst maxed out."
        },
        {
            "key": "APP_ERROR_1122",
            "value": "Selected equipment item cannot be equipped."
        },
        {
            "key": "APP_ERROR_1123",
            "value": "Selected equipment item is equipped to another slot."
        },
        {
            "key": "APP_ERROR_1124",
            "value": "Selected equipment item cannot be equipped."
        },
        {
            "key": "APP_ERROR_1125",
            "value": "Selected equipment item cannot be equipped."
        },
        {
            "key": "APP_ERROR_1126",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_1127",
            "value": "Unit not found."
        },
        {
            "key": "APP_ERROR_1133",
            "value": "Appearance change failed.<br>Conditions to Equip have not been met."
        },
        {
            "key": "APP_ERROR_1200",
            "value": "Unknown esper."
        },
        {
            "key": "APP_ERROR_1201",
            "value": "Esper's level is insufficient."
        },
        {
            "key": "APP_ERROR_1202",
            "value": "Esper's SP is insufficient."
        },
        {
            "key": "APP_ERROR_1203",
            "value": "Esper is fully awakened."
        },
        {
            "key": "APP_ERROR_1204",
            "value": "Selected Ability Board cannot be unlocked."
        },
        {
            "key": "APP_ERROR_1205",
            "value": "Selected Ability Board is already unlocked."
        },
        {
            "key": "APP_ERROR_1300",
            "value": "Selected equipment item does not exist."
        },
        {
            "key": "APP_ERROR_1301",
            "value": "Equipment is fully awakened."
        },
        {
            "key": "APP_ERROR_1302",
            "value": "Equipment's level maxed out."
        },
        {
            "key": "APP_ERROR_1303",
            "value": "Equipment's level is insufficient."
        },
        {
            "key": "APP_ERROR_1304",
            "value": "Equipment slots maxed out."
        },
        {
            "key": "APP_ERROR_1305",
            "value": "Equipment ID not specified."
        },
        {
            "key": "APP_ERROR_1306",
            "value": "Equipment crafting failed."
        },
        {
            "key": "APP_ERROR_1307",
            "value": "Equipment dismantle failed."
        },
        {
            "key": "APP_ERROR_1308",
            "value": "Equipment enhancement failed."
        },
        {
            "key": "APP_ERROR_1309",
            "value": "Equipment sale failed."
        },
        {
            "key": "APP_ERROR_1310",
            "value": "Crafting for this piece of equipment has been temporarily suspended."
        },
        {
            "key": "APP_ERROR_1311",
            "value": "Some of the selected equipment cannot be sold."
        },
        {
            "key": "APP_ERROR_1400",
            "value": "Vision card does not exist."
        },
        {
            "key": "APP_ERROR_1401",
            "value": "Vision card is fully awakened."
        },
        {
            "key": "APP_ERROR_1402",
            "value": "Vision card's level maxed out."
        },
        {
            "key": "APP_ERROR_1403",
            "value": "Vision card's level is insufficient."
        },
        {
            "key": "APP_ERROR_1404",
            "value": "Vision card slots maxed out."
        },
        {
            "key": "APP_ERROR_1405",
            "value": "Vision card ID not specified."
        },
        {
            "key": "APP_ERROR_1406",
            "value": "Vision card enhancement failed."
        },
        {
            "key": "APP_ERROR_1407",
            "value": "Vision card sale failed."
        },
        {
            "key": "APP_ERROR_1500",
            "value": "Present not found."
        },
        {
            "key": "APP_ERROR_1501",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_1502",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_1503",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_1600",
            "value": "Party not found."
        },
        {
            "key": "APP_ERROR_1601",
            "value": "Party formation failed."
        },
        {
            "key": "APP_ERROR_1602",
            "value": "Party formation failed."
        },
        {
            "key": "APP_ERROR_1603",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_1700",
            "value": "Friend does not exist."
        },
        {
            "key": "APP_ERROR_1701",
            "value": "Max number of Friends has been reached. Unable to send Friend Request."
        },
        {
            "key": "APP_ERROR_1702",
            "value": "Max number of Friends has been reached. Unable to accept Friend Request."
        },
        {
            "key": "APP_ERROR_1703",
            "value": "Friend Request does not exist."
        },
        {
            "key": "APP_ERROR_1704",
            "value": "ID not specified."
        },
        {
            "key": "APP_ERROR_1705",
            "value": "Searched player not found."
        },
        {
            "key": "APP_ERROR_1706",
            "value": "Searched Player ID is this account's Player ID."
        },
        {
            "key": "APP_ERROR_1707",
            "value": "Unable to claim Friend Gift."
        },
        {
            "key": "APP_ERROR_1708",
            "value": "Desired Friend Gift does not exist."
        },
        {
            "key": "APP_ERROR_1709",
            "value": "Friend Request failed to send."
        },
        {
            "key": "APP_ERROR_1710",
            "value": "You are blocking this player."
        },
        {
            "key": "APP_ERROR_1800",
            "value": "Blocked List does not exist."
        },
        {
            "key": "APP_ERROR_1801",
            "value": "Max number of blocked players has been reached. <br>Unable to add any more players to the Blocked List."
        },
        {
            "key": "APP_ERROR_1802",
            "value": "Selected Player ID is this account's Player ID."
        },
        {
            "key": "APP_ERROR_2000",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2001",
            "value": "Cost limit exceeded."
        },
        {
            "key": "APP_ERROR_2002",
            "value": "Quest not active."
        },
        {
            "key": "APP_ERROR_2003",
            "value": "Could not begin quest. Quest not active."
        },
        {
            "key": "APP_ERROR_2004",
            "value": "Could not begin quest. Challenge conditions have not been met."
        },
        {
            "key": "APP_ERROR_2005",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2006",
            "value": "Unknown unit in party formation."
        },
        {
            "key": "APP_ERROR_2007",
            "value": "Failed to restore to interrupted point."
        },
        {
            "key": "APP_ERROR_2008",
            "value": "Cannot continue."
        },
        {
            "key": "APP_ERROR_2009",
            "value": "Attempt limit has been reached for today."
        },
        {
            "key": "APP_ERROR_2010",
            "value": "Formation rules not met."
        },
        {
            "key": "APP_ERROR_2011",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2012",
            "value": "Selected companion not found."
        },
        {
            "key": "APP_ERROR_2100",
            "value": "Room not found."
        },
        {
            "key": "APP_ERROR_2101",
            "value": "Not entered into room."
        },
        {
            "key": "APP_ERROR_2102",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_2103",
            "value": "The host has not yet decided to embark."
        },
        {
            "key": "APP_ERROR_2104",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2105",
            "value": "Members have already embarked."
        },
        {
            "key": "APP_ERROR_2106",
            "value": "Could not return. Battle has already ended."
        },
        {
            "key": "APP_ERROR_2150",
            "value": "Skip ticket cannot be used."
        },
        {
            "key": "APP_ERROR_2151",
            "value": "Skip ticket cannot be used because not all missions have been cleared."
        },
        {
            "key": "APP_ERROR_2152",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_2153",
            "value": "Companion update failed."
        },
        {
            "key": "APP_ERROR_2161",
            "value": "Quest has been closed."
        },
        {
            "key": "APP_ERROR_2163",
            "value": "An error has occurred during the skip operation.<br>The result immediately before the error occurred will be reflected.<br>Returning to the Title screen."
        },
        {
            "key": "APP_ERROR_2200",
            "value": "Raid not found."
        },
        {
            "key": "APP_ERROR_2201",
            "value": "Raid challenge period has concluded."
        },
        {
            "key": "APP_ERROR_2202",
            "value": "Raid reward claim period has expired."
        },
        {
            "key": "APP_ERROR_2203",
            "value": "Raid ranking period has concluded."
        },
        {
            "key": "APP_ERROR_2204",
            "value": "Raid boss not found."
        },
        {
            "key": "APP_ERROR_2205",
            "value": "Unknown raid boss."
        },
        {
            "key": "APP_ERROR_2206",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_2207",
            "value": "Raid boss escaped."
        },
        {
            "key": "APP_ERROR_2208",
            "value": "Unknown room."
        },
        {
            "key": "APP_ERROR_2209",
            "value": "Not in an encounter with a raid boss."
        },
        {
            "key": "APP_ERROR_2210",
            "value": "There is already a raid boss being challenged."
        },
        {
            "key": "APP_ERROR_2211",
            "value": "Room not found."
        },
        {
            "key": "APP_ERROR_2212",
            "value": "Raid boss has already been defeated."
        },
        {
            "key": "APP_ERROR_2213",
            "value": "Unable to challenge because you are not the raid leader."
        },
        {
            "key": "APP_ERROR_2214",
            "value": "Could not challenge the raid boss."
        },
        {
            "key": "APP_ERROR_2215",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2216",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2217",
            "value": "Total challenge limit has been reached."
        },
        {
            "key": "APP_ERROR_2218",
            "value": "No members in the room."
        },
        {
            "key": "APP_ERROR_2219",
            "value": "Raid Quest not found."
        },
        {
            "key": "APP_ERROR_2220",
            "value": "Unknown Raid Quest."
        },
        {
            "key": "APP_ERROR_2221",
            "value": "Cannot start because there is already an ongoing Raid Quest."
        },
        {
            "key": "APP_ERROR_2222",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2223",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2224",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2225",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2226",
            "value": "Raid Orb restoration limit exceeded.<br>(Visiore)"
        },
        {
            "key": "APP_ERROR_2227",
            "value": "Raid Orbs cannot be further restored."
        },
        {
            "key": "APP_ERROR_2228",
            "value": "Unable to restore RP with this item."
        },
        {
            "key": "APP_ERROR_2229",
            "value": "Raid Orb restoration limit exceeded.<br>(Item)"
        },
        {
            "key": "APP_ERROR_2230",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2231",
            "value": "There is already a Challenger for this Encounter."
        },
        {
            "key": "APP_ERROR_2232",
            "value": "Failed to claim raid rewards."
        },
        {
            "key": "APP_ERROR_2233",
            "value": "Raid boss has not been defeated."
        },
        {
            "key": "APP_ERROR_2234",
            "value": "Could not call for reinforcements."
        },
        {
            "key": "APP_ERROR_2235",
            "value": "Could not enter the room because members have already embarked."
        },
        {
            "key": "APP_ERROR_2236",
            "value": "Limit has been reached on the number of Raid Quests that can be challenged simultaneously."
        },
        {
            "key": "APP_ERROR_2237",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_2238",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2239",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2240",
            "value": "Limit has been reached on becoming a raid leader."
        },
        {
            "key": "APP_ERROR_2241",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_2243",
            "value": "Could not return. Battle has already ended."
        },
        {
            "key": "APP_ERROR_2300",
            "value": "Shop not found. It is not open at this time."
        },
        {
            "key": "APP_ERROR_2301",
            "value": "Whimsy Shop not found.<br>It is not open at this time."
        },
        {
            "key": "APP_ERROR_2302",
            "value": "Total purchasable number exceeded."
        },
        {
            "key": "APP_ERROR_2303",
            "value": "You have attempted to purchase an unknown item."
        },
        {
            "key": "APP_ERROR_2304",
            "value": "Total purchasable number exceeded."
        },
        {
            "key": "APP_ERROR_2305",
            "value": "Total purchasable number exceeded."
        },
        {
            "key": "APP_ERROR_2306",
            "value": "Product is not available for sale."
        },
        {
            "key": "APP_ERROR_2307",
            "value": "The shop has been updated."
        },
        {
            "key": "APP_ERROR_2308",
            "value": "Shop not found."
        },
        {
            "key": "APP_ERROR_2309",
            "value": "Shop error. (Failed to retrieve raffle information.)"
        },
        {
            "key": "APP_ERROR_2310",
            "value": "Invalid payment type selected."
        },
        {
            "key": "APP_ERROR_2311",
            "value": "Shop error. (Failed to retrieve raffle information.)"
        },
        {
            "key": "APP_ERROR_2312",
            "value": "Shop error. (Failed to retrieve raffle information.)"
        },
        {
            "key": "APP_ERROR_2313",
            "value": "Shop error. (Failed to retrieve raffle information.)"
        },
        {
            "key": "APP_ERROR_2314",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2324",
            "value": "Could not purchase (exchange)."
        },
        {
            "key": "APP_ERROR_2327",
            "value": "Cannot purchase quantity that exceeds purchasable (exchangeable) limit in one transaction."
        },
        {
            "key": "APP_ERROR_2328",
            "value": "Shop lineup has been updated."
        },
        {
            "key": "APP_ERROR_2400",
            "value": "Summon could not be retrieved."
        },
        {
            "key": "APP_ERROR_2401",
            "value": "Summon could not be retrieved."
        },
        {
            "key": "APP_ERROR_2402",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2403",
            "value": "The Step Up Summon<br>could not be performed properly<br>due to a connection error."
        },
        {
            "key": "APP_ERROR_2404",
            "value": "Summon limit has been reached."
        },
        {
            "key": "APP_ERROR_2405",
            "value": "Summon limit has been reached."
        },
        {
            "key": "APP_ERROR_2406",
            "value": "Unable to summon. Insufficient Visiore or tickets."
        },
        {
            "key": "APP_ERROR_2407",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2408",
            "value": "Summon period has expired."
        },
        {
            "key": "APP_ERROR_2409",
            "value": "Summon error. (Already summoned.)"
        },
        {
            "key": "APP_ERROR_2410",
            "value": "Summon error. (Attempting to re-summon.)"
        },
        {
            "key": "APP_ERROR_2411",
            "value": "Re-summoning limit has been reached."
        },
        {
            "key": "APP_ERROR_2412",
            "value": "Unknown summon."
        },
        {
            "key": "APP_ERROR_2413",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2414",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2415",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2416",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2417",
            "value": "Summon could not be retrieved."
        },
        {
            "key": "APP_ERROR_2418",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2419",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2420",
            "value": "Summon error. (Failed to retrieve raffle information.)"
        },
        {
            "key": "APP_ERROR_2421",
            "value": "Summon error."
        },
        {
            "key": "APP_ERROR_2422",
            "value": "Summon error."
        },
        {
            "key": "APP_ERROR_2423",
            "value": "Summon error."
        },
        {
            "key": "APP_ERROR_2424",
            "value": "Summon error."
        },
        {
            "key": "APP_ERROR_2427",
            "value": "Cannot be retrieved as the comeback period has passed."
        },
        {
            "key": "APP_ERROR_2501",
            "value": "Challenge mission not available at this time."
        },
        {
            "key": "APP_ERROR_2531",
            "value": "Mission not available at this time."
        },
        {
            "key": "APP_ERROR_2560",
            "value": "Unlock conditions have not been met."
        },
        {
            "key": "APP_ERROR_2600",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2601",
            "value": "Insufficient Visiore."
        },
        {
            "key": "APP_ERROR_2602",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2603",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2604",
            "value": "You have attempted to head out into an unknown area."
        },
        {
            "key": "APP_ERROR_2605",
            "value": "Cannot perform high-speed expedition with this item."
        },
        {
            "key": "APP_ERROR_2606",
            "value": "Limit has been reached on high-speed expeditions for today."
        },
        {
            "key": "APP_ERROR_2607",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2608",
            "value": "Item cannot be recovered."
        },
        {
            "key": "APP_ERROR_2609",
            "value": "Unknown unit."
        },
        {
            "key": "APP_ERROR_2700",
            "value": "Please wait a while before entering."
        },
        {
            "key": "APP_ERROR_2701",
            "value": "Channel not found."
        },
        {
            "key": "APP_ERROR_2702",
            "value": "Unknown stamp."
        },
        {
            "key": "APP_ERROR_2703",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_2704",
            "value": "This account has violated the Terms of Use and is unable to use the chat function."
        },
        {
            "key": "APP_ERROR_2800",
            "value": "Date does not exist."
        },
        {
            "key": "APP_ERROR_2900",
            "value": "Hosting period is different."
        },
        {
            "key": "APP_ERROR_2901",
            "value": "Party not set."
        },
        {
            "key": "APP_ERROR_2902",
            "value": "Unauthorized party."
        },
        {
            "key": "APP_ERROR_2903",
            "value": "Unauthorized battle results."
        },
        {
            "key": "APP_ERROR_3000",
            "value": "Player already belongs to a guild."
        },
        {
            "key": "APP_ERROR_3001",
            "value": "Guild not found."
        },
        {
            "key": "APP_ERROR_3002",
            "value": "You do not belong to a guild."
        },
        {
            "key": "APP_ERROR_3003",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_3004",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3005",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3006",
            "value": "Unknown emblem."
        },
        {
            "key": "APP_ERROR_3007",
            "value": "Once you leave a guild, you must wait<br>before you are able to join again.<br><br>The wait time before you can<br>rejoin a guild is 24 hours."
        },
        {
            "key": "APP_ERROR_3008",
            "value": "Limit has been reached on the number of guild members."
        },
        {
            "key": "APP_ERROR_3009",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3010",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3011",
            "value": "Guild Leader cannot leave the guild. Transfer leadership before leaving the guild."
        },
        {
            "key": "APP_ERROR_3012",
            "value": "Already in attendance."
        },
        {
            "key": "APP_ERROR_3013",
            "value": "Attendance function not yet unlocked."
        },
        {
            "key": "APP_ERROR_3014",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3015",
            "value": "Max number of guild Sub Leaders reached."
        },
        {
            "key": "APP_ERROR_3016",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3017",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3018",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3019",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3020",
            "value": "Entry request submitted to this guild."
        },
        {
            "key": "APP_ERROR_3021",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3022",
            "value": "Guild entry request not found."
        },
        {
            "key": "APP_ERROR_3023",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3025",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3026",
            "value": "Already claimed."
        },
        {
            "key": "APP_ERROR_3027",
            "value": "Already claimed."
        },
        {
            "key": "APP_ERROR_3028",
            "value": "Gift has expired."
        },
        {
            "key": "APP_ERROR_3029",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3030",
            "value": "Not yet unlocked."
        },
        {
            "key": "APP_ERROR_3031",
            "value": "Max level reached. Cannot enhance further."
        },
        {
            "key": "APP_ERROR_3032",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3033",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3034",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3035",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3036",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3037",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_3038",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_3039",
            "value": "Entry conditions have not been met."
        },
        {
            "key": "APP_ERROR_3040",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3041",
            "value": "You do not have permission."
        },
        {
            "key": "APP_ERROR_3042",
            "value": "Guild name is too long."
        },
        {
            "key": "APP_ERROR_3043",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3044",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3045",
            "value": "Guild Unlock conditions have not been met."
        },
        {
            "key": "APP_ERROR_3046",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3047",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3048",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3049",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3050",
            "value": "You have already updated to this emblem."
        },
        {
            "key": "APP_ERROR_3051",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3059",
            "value": "Outside of acquisition period."
        },
        {
            "key": "APP_ERROR_3060",
            "value": "Could not begin Guild Trial."
        },
        {
            "key": "APP_ERROR_3061",
            "value": "Could not begin Guild Trial."
        },
        {
            "key": "APP_ERROR_3062",
            "value": "Could not begin Guild Trial."
        },
        {
            "key": "APP_ERROR_3063",
            "value": "Could not begin Guild Trial."
        },
        {
            "key": "APP_ERROR_3064",
            "value": "Player is not a newcomer and cannot be promoted to Member."
        },
        {
            "key": "APP_ERROR_3065",
            "value": "Usage limit has been reached."
        },
        {
            "key": "APP_ERROR_3100",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3101",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3102",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3103",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3104",
            "value": "Opponent information has been updated. Battle could not be started"
        },
        {
            "key": "APP_ERROR_3105",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3106",
            "value": "You cannot disband a guild<br>during a guild battle."
        },
        {
            "key": "APP_ERROR_3107",
            "value": "Guild member information has been updated. Returning to the home screen to reacquire data."
        },
        {
            "key": "APP_ERROR_3108",
            "value": "Battle time has passed."
        },
        {
            "key": "APP_ERROR_3109",
            "value": "Limited Guild Battles have begun."
        },
        {
            "key": "APP_ERROR_3200",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3201",
            "value": "Cannot purchase."
        },
        {
            "key": "APP_ERROR_3202",
            "value": "Cannot purchase."
        },
        {
            "key": "APP_ERROR_3203",
            "value": "Already purchased."
        },
        {
            "key": "APP_ERROR_3204",
            "value": "Insufficient Visiore."
        },
        {
            "key": "APP_ERROR_3205",
            "value": "Cannot purchase."
        },
        {
            "key": "APP_ERROR_3300",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3301",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3302",
            "value": "Event period not active."
        },
        {
            "key": "APP_ERROR_3303",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3304",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3305",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3306",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3307",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3308",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3309",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3310",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3311",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3312",
            "value": "Battle period has passed."
        },
        {
            "key": "APP_ERROR_3400",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3401",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3402",
            "value": "Event period not active."
        },
        {
            "key": "APP_ERROR_3403",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3404",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3405",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3406",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3407",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3408",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3409",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3410",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3411",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3412",
            "value": "Battle period has passed."
        },
        {
            "key": "APP_ERROR_3500",
            "value": "Could not commence duel."
        },
        {
            "key": "APP_ERROR_3501",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3502",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3503",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3504",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3600",
            "value": "Tutorial not found."
        },
        {
            "key": "APP_ERROR_3601",
            "value": "Cannot begin tutorial."
        },
        {
            "key": "APP_ERROR_3602",
            "value": "Tutorial has already finished."
        },
        {
            "key": "APP_ERROR_3700",
            "value": "Unidentified error."
        },
        {
            "key": "APP_ERROR_3701",
            "value": "Locked."
        },
        {
            "key": "APP_ERROR_3800",
            "value": "You do not have a high enough rank to issue invite codes."
        },
        {
            "key": "APP_ERROR_3801",
            "value": "You do not have a high enough rank to register invite codes."
        },
        {
            "key": "APP_ERROR_3802",
            "value": "Player has reached max invite recipients."
        },
        {
            "key": "APP_ERROR_3803",
            "value": "Entered invite code is incorrect."
        },
        {
            "key": "APP_ERROR_3804",
            "value": "Another invite code has already been registered."
        },
        {
            "key": "APP_ERROR_4027",
            "value": "Truststones that are equipped to favorites cannot be used as enhancing materials."
        },
        {
            "key": "APP_ERROR_4028",
            "value": "Equipped Truststones cannot be used as enhancing materials."
        },
        {
            "key": "APP_ERROR_4102",
            "value": "This exchange rate is unavailable at this time."
        },
        {
            "key": "APP_ERROR_4106",
            "value": "Outside of campaign period."
        },
        {
            "key": "APP_ERROR_5101",
            "value": "Cannot start battle."
        },
        {
            "key": "APP_ERROR_5102",
            "value": "Cannot start battle."
        },
        {
            "key": "APP_ERROR_5103",
            "value": "Party Formation cost limit exceeded."
        },
        {
            "key": "APP_ERROR_5104",
            "value": "Party Formation member limit exceeded."
        },
        {
            "key": "APP_ERROR_5105",
            "value": "Cannot attempt."
        },
        {
            "key": "APP_ERROR_5106",
            "value": "Your Party includes KO’d units."
        },
        {
            "key": "APP_ERROR_5107",
            "value": "Cannot restart battle."
        },
        {
            "key": "APP_ERROR_5108",
            "value": "Cannot restore."
        },
        {
            "key": "APP_ERROR_5109",
            "value": "Cannot try again from the beginning."
        },
        {
            "key": "APP_ERROR_5110",
            "value": "Cannot continue."
        },
        {
            "key": "APP_ERROR_5111",
            "value": "Event Period Not Active."
        },
        {
            "key": "APP_ERROR_5112",
            "value": "Formation rules not met."
        },
        {
            "key": "APP_ERROR_5201",
            "value": "Code does not exist."
        },
        {
            "key": "APP_ERROR_5202",
            "value": "Outside of campaign period."
        },
        {
            "key": "APP_ERROR_5203",
            "value": "Exceeds campaign's max receipt limit."
        },
        {
            "key": "APP_ERROR_5204",
            "value": "Serial code already used."
        },
        {
            "key": "APP_ERROR_5205",
            "value": "Invalid platform."
        },
        {
            "key": "APP_ERROR_5300",
            "value": "Target party is unauthorized."
        },
        {
            "key": "APP_ERROR_5301",
            "value": "Insufficient turns."
        },
        {
            "key": "APP_ERROR_5302",
            "value": "The party has changed.<br>Please refresh and try again."
        },
        {
            "key": "APP_ERROR_5303",
            "value": "Battle time has passed."
        },
        {
            "key": "APP_ERROR_5304",
            "value": "Limited Guild Battles have ended."
        },
        {
            "key": "APP_ERROR_5305",
            "value": "Target party has already been disclosed."
        },
        {
            "key": "APP_ERROR_5306",
            "value": "Target party's action count is maxed out."
        },
        {
            "key": "APP_ERROR_5307",
            "value": "Target party's ability uses are maxed out."
        },
        {
            "key": "ALREADY_CONNECTED",
            "value": "The account on this social platform is already bound to another player's account."
        },
        {
            "key": "SNS_ACCOUNT_LIMIT_REACHED",
            "value": "SNS account limit reached"
        },
        {
            "key": "SNS_CONNECTION_LIMIT_REACHED",
            "value": "SNS account connection limit reached"
        },
        {
            "key": "SNS_LIMIT_REACHED",
            "value": "SNS limit reached"
        },
        {
            "key": "GL_ACCOUNT_BAN_TEMP_TITLE",
            "value": "Temporary Ban"
        },
        {
            "key": "GL_ACCOUNT_BAN_PERMA_TITLE",
            "value": "Permanent Ban"
        },
        {
            "key": "GL_ACCOUNT_BAN_TEMP_MESSAGE",
            "value": "Your account has been suspended until {0}, (PST).<br><br>For details, please contact Customer Support through the Title Screen by tapping [Support] > [Inquiries]."
        },
        {
            "key": "GL_ACCOUNT_BAN_PERMA_MESSAGE",
            "value": "Your account has been suspended.<br><br>For details, please contact Customer Support through the Title Screen by tapping [Support] > [Inquiries]."
        },
        {
            "key": "GL_ACCOUNT_BAN_TITLE",
            "value": "Account Suspension"
        },
        {
            "key": "GL_ACCOUNT_BAN_MSG_SUPPORT",
            "value": "For details, please contact Customer Support through the Title Screen by tapping [Support] > [Inquiries]."
        },
        {
            "key": "GL_ACCOUNT_BAN_DEFAULT",
            "value": "Your account has been suspended."
        },
        {
            "key": "GL_ACCOUNT_BAN_PERIOD",
            "value": "{0} day(s) left (Until: {1}, World Time (PST))"
        },
        {
            "key": "GL_ACCOUNT_BAN_PERMA_MESSAGE_2",
            "value": "Period: Permanent"
        },
        {
            "key": "APP_ERROR_5308",
            "value": "You have exceeded the max number of applicable supports."
        },
        {
            "key": "APP_ERROR_5309",
            "value": "This support cannot be applied again to the same party."
        },
        {
            "key": "APP_ERROR_5310",
            "value": "Outside of Limited Guild Battle formation period."
        },
        {
            "key": "APP_ERROR_5600",
            "value": "Outside of Event Period Error"
        },
        {
            "key": "APP_ERROR_5601",
            "value": "Currently Outside of Guild Raid Period Error"
        },
        {
            "key": "APP_ERROR_5602",
            "value": "Outside of Battle Period Error"
        },
        {
            "key": "APP_ERROR_5603",
            "value": "Outside of Trial Battle Period Error"
        },
        {
            "key": "APP_ERROR_5604",
            "value": "Battle that Exceeded the Action Count was Held"
        },
        {
            "key": "APP_ERROR_5605",
            "value": "Boss Already Defeated"
        },
        {
            "key": "APP_ERROR_5606",
            "value": "Interrupted Quest Cannot Be Resumed Normally (Interrupted Quest Data Other than Guild Raid Remains)"
        },
        {
            "key": "APP_ERROR_5607",
            "value": "Boss Battle Not Unlocked"
        },
        {
            "key": "APP_ERROR_5608",
            "value": "Defect in the Interrupted Quest Data "
        },
        {
            "key": "APP_ERROR_5609",
            "value": "Cannot Subtract BP (BP Shortage)"
        },
        {
            "key": "APP_ERROR_5700",
            "value": "Some of the details entered cannot be used."
        },
        {
            "key": "APP_ERROR_5703",
            "value": "A scouting offer has already been sent."
        },
        {
            "key": "APP_ERROR_5704",
            "value": "Max number of Guild Members reached. Cannot scout."
        },
        {
            "key": "APP_ERROR_5705",
            "value": "Already in a Guild. Cannot scout."
        },
        {
            "key": "APP_ERROR_5800",
            "value": "Target party is unauthorized."
        },
        {
            "key": "APP_ERROR_5801",
            "value": "Insufficient action count."
        },
        {
            "key": "APP_ERROR_5802",
            "value": "The party has changed.<br>Please refresh and try again."
        },
        {
            "key": "APP_ERROR_5803",
            "value": "Battle time has passed."
        },
        {
            "key": "APP_ERROR_5804",
            "value": "Guild Battle Supremacy has ended."
        },
        {
            "key": "APP_ERROR_5805",
            "value": "Target party has already been disclosed."
        },
        {
            "key": "APP_ERROR_5806",
            "value": "Target party's action count is maxed out."
        },
        {
            "key": "APP_ERROR_5807",
            "value": "Target party's ability uses are maxed out."
        },
        {
            "key": "APP_ERROR_5808",
            "value": "You have exceeded the max number of applicable supports."
        },
        {
            "key": "APP_ERROR_5809",
            "value": "This support cannot be applied again to the same party."
        },
        {
            "key": "APP_ERROR_5810",
            "value": "Outside of Guild Battle Supremacy formation period."
        },
        {
            "key": "APP_ERROR_6002",
            "value": "Summon cannot be performed because the event duration has passed, or due to other reasons."
        }
    ]
}